export const description = 'Display Philippine Stocker Market Stock Info by Symbol'
export const bmcline = 'Love this project? Please consider to support the \n development by means of coffee!'
export const bmcurl = 'https://www.buymeacoffee.com/ianvizarra'
export const twitterline = 'Follow me on twitter for more updates!'
export const twitterhandle = '@ianvizarra'
